[package]
name = "cairo-svgpath"
version = "0.1.0"
authors = ["Jakub Kądziołka <kuba@kadziolka.net>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "^0.15"
proc-macro2 = "^0.4"
quote = "^0.6"
svgtypes = "^0.4"
